from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

supply_design = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'USB_C_Receptacle_USB2.0_16P', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USB_C_Receptacle_USB2.0_16P'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_USB:USB_C_Receptacle_GCT_USB4105-xx-A_16P_TopMnt_Horizontal', 'keywords':'usb universal serial bus type-C USB2.0', 'description':'USB 2.0-only 16P Type-C Receptacle connector', 'datasheet':'https://www.usb.org/sites/default/files/documents/usb_type-c.zip', 'pins':[
            Pin(num='A1',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='A4',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='A5',name='CC1',func=pin_types.BIDIR,unit=1),
            Pin(num='A6',name='D+',func=pin_types.BIDIR,unit=1),
            Pin(num='A7',name='D-',func=pin_types.BIDIR,unit=1),
            Pin(num='A8',name='SBU1',func=pin_types.BIDIR,unit=1),
            Pin(num='A9',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='A12',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='B1',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='B4',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='B5',name='CC2',func=pin_types.BIDIR,unit=1),
            Pin(num='B6',name='D+',func=pin_types.BIDIR,unit=1),
            Pin(num='B7',name='D-',func=pin_types.BIDIR,unit=1),
            Pin(num='B8',name='SBU2',func=pin_types.BIDIR,unit=1),
            Pin(num='B9',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='B12',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='SH',name='SHIELD',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_SMD:C_1210_3225Metric', 'keywords':'cap capacitor', 'description':'Unpolarized capacitor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'D_Zener', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'D_Zener'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'Diode_SMD:D_SMB', 'keywords':'diode', 'description':'Zener diode', 'datasheet':'', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'AP33772S', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AP33772S'}), 'ref_prefix':'U', 'fplist':['Package_DFN_QFN:QFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.7mm_ThermalVias'], 'footprint':'Package_DFN_QFN:QFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.7mm_ThermalVias', 'keywords':'', 'description':'USB PD 3.1 EPR (28 V) sink controller, I2C host control', 'datasheet':'', 'pins':[
            Pin(num='1',name='ISENP',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='3',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='4',name='SDA',func=pin_types.BIDIR,unit=1),
            Pin(num='5',name='SCL',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='FLIP',func=pin_types.OUTPUT,unit=1),
            Pin(num='7',name='GPIO',func=pin_types.BIDIR,unit=1),
            Pin(num='8',name='LED',func=pin_types.OUTPUT,unit=1),
            Pin(num='9',name='INT',func=pin_types.OUTPUT,unit=1),
            Pin(num='10',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='11',name='VSEL',func=pin_types.PASSIVE,unit=1),
            Pin(num='12',name='V18',func=pin_types.PWROUT,unit=1),
            Pin(num='13',name='OTP',func=pin_types.PASSIVE,unit=1),
            Pin(num='14',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='15',name='IFB',func=pin_types.PASSIVE,unit=1),
            Pin(num='16',name='CC2',func=pin_types.BIDIR,unit=1),
            Pin(num='17',name='CC1',func=pin_types.BIDIR,unit=1),
            Pin(num='18',name='DN',func=pin_types.BIDIR,unit=1),
            Pin(num='19',name='DP',func=pin_types.BIDIR,unit=1),
            Pin(num='20',name='V5V',func=pin_types.PWROUT,unit=1),
            Pin(num='21',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='22',name='VOUT',func=pin_types.INPUT,unit=1),
            Pin(num='23',name='PWR_EN',func=pin_types.OUTPUT,unit=1),
            Pin(num='24',name='VCC',func=pin_types.PWRIN,unit=1),
            Pin(num='25',name='EP',func=pin_types.PWRIN,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'Resistor_SMD:R_2512_6332Metric', 'keywords':'R res resistor', 'description':'Resistor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'TestPoint', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TestPoint'}), 'ref_prefix':'TP', 'fplist':[''], 'footprint':'TestPoint:TestPoint_Pad_D1.0mm', 'keywords':'test point tp', 'description':'test point', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'BAT54W', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BAT54W'}), 'ref_prefix':'D', 'fplist':['Package_TO_SOT_SMD:SOT-323_SC-70'], 'footprint':'Package_TO_SOT_SMD:SOT-323_SC-70', 'keywords':'schottky diode', 'description':'Schottky barrier diode, SOT-323', 'datasheet':'https://assets.nexperia.com/documents/data-sheet/BAT54W_SER.pdf', 'pins':[
            Pin(num='1',name='A',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='3',name='K',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Thermistor_NTC', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Thermistor_NTC'}), 'ref_prefix':'TH', 'fplist':[''], 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':'thermistor NTC resistor sensor RTD', 'description':'Temperature dependent resistor, negative temperature coefficient', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'LED', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LED'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'LED_SMD:LED_0805_2012Metric', 'keywords':'LED diode', 'description':'Light emitting diode', 'datasheet':'', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'LM74800', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LM74800'}), 'ref_prefix':'U', 'fplist':['Package_SON:WSON-12-1EP_3x3mm_P0.5mm_EP1.5x2.5mm'], 'footprint':'Package_SON:WSON-12-1EP_3x3mm_P0.5mm_EP1.5x2.5mm', 'keywords':'', 'description':'Ideal diode + load switch controller, 65 V', 'datasheet':'', 'pins':[
            Pin(num='1',name='DGATE',func=pin_types.OUTPUT,unit=1),
            Pin(num='2',name='A',func=pin_types.INPUT,unit=1),
            Pin(num='3',name='VSNS',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='SW',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='OV',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='EN/UVLO',func=pin_types.INPUT,unit=1),
            Pin(num='7',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='8',name='HGATE',func=pin_types.OUTPUT,unit=1),
            Pin(num='9',name='OUT',func=pin_types.INPUT,unit=1),
            Pin(num='10',name='VS',func=pin_types.PWRIN,unit=1),
            Pin(num='11',name='CAP',func=pin_types.PASSIVE,unit=1),
            Pin(num='12',name='C',func=pin_types.INPUT,unit=1),
            Pin(num='13',name='RTN',func=pin_types.NOCONNECT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'CSD18532Q5B', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'CSD18532Q5B'}), 'ref_prefix':'Q', 'fplist':['', 'Package_TO_SOT_SMD:TDSON-8-1'], 'footprint':'Package_TO_SOT_SMD:TDSON-8-1', 'keywords':'NexFET Power MOSFET N-MOS', 'description':'100A Id, 60V Vds, NexFET N-Channel Power MOSFET, 3.2mOhm Ron, 44nC Qg(typ), SON8 5x6mm', 'datasheet':'http://www.ti.com/lit/gpn/csd18532q5b', 'pins':[
            Pin(num='1',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='G',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='D',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x02', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x02'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_AMASS:AMASS_XT60PW-M_1x02_P7.20mm_Horizontal', 'keywords':'connector', 'description':'Generic connector, single row, 01x02, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'BSC040N10NS5', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BSC040N10NS5'}), 'ref_prefix':'Q', 'fplist':['', 'Package_TO_SOT_SMD:TDSON-8-1'], 'footprint':'Package_SON:Infineon_PG-TDSON-8_6.15x5.15mm', 'keywords':'OptiMOS Power MOSFET N-MOS', 'description':'100A Id, 100V Vds, OptiMOS N-Channel Power MOSFET, 4.0mOhm Ron, Qg (typ) 58.0nC, PG-TDSON-8', 'datasheet':'http://www.infineon.com/dgdl/Infineon-BSC040N10NS5-DS-v02_01-EN.pdf?fileId=5546d4624a0bf290014a0fbcee2e6b38', 'pins':[
            Pin(num='1',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='G',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='D',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'INA228', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'INA228'}), 'ref_prefix':'U', 'fplist':['Package_SO:TSSOP-10_3x3mm_P0.5mm', 'Package_SO:TSSOP-10_3x3mm_P0.5mm'], 'footprint':'Package_SO:TSSOP-10_3x3mm_P0.5mm', 'keywords':'ADC I2C 20-Bit Oversampling Current Shunt', 'description':'High-Side or Low-Side Measurement, Bi-Directional Current and Power Monitor (0-85V) with I2C, SMBus-, and PMBus-Compatible Interface, TSSOP-10 (Texas DGS0010A / VSSOP)', 'datasheet':'https://www.ti.com/lit/ds/symlink/ina228.pdf', 'pins':[
            Pin(num='1',name='A1',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='A0',func=pin_types.INPUT,unit=1),
            Pin(num='3',name='~{Alert}',func=pin_types.OPENCOLL,unit=1),
            Pin(num='4',name='SDA',func=pin_types.BIDIR,unit=1),
            Pin(num='5',name='SCL',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='VS',func=pin_types.PWRIN,unit=1),
            Pin(num='7',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='8',name='Vbus',func=pin_types.INPUT,unit=1),
            Pin(num='9',name='Vin-',func=pin_types.INPUT,unit=1),
            Pin(num='10',name='Vin+',func=pin_types.INPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'LTC7803', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LTC7803'}), 'ref_prefix':'U', 'fplist':['Package_SO:MSOP-16-1EP_3x4.039mm_P0.5mm_EP1.651x2.845mm_ThermalVias'], 'footprint':'Package_SO:MSOP-16-1EP_3x4.039mm_P0.5mm_EP1.651x2.845mm_ThermalVias', 'keywords':'', 'description':'40 V synchronous buck controller, 100 % duty', 'datasheet':'', 'pins':[
            Pin(num='1',name='TRACK/SS',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='SENSE+',func=pin_types.INPUT,unit=1),
            Pin(num='3',name='SENSE-',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='VFB',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='ITH',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='RUN',func=pin_types.INPUT,unit=1),
            Pin(num='7',name='FREQ',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',name='PLLIN/SPREAD',func=pin_types.INPUT,unit=1),
            Pin(num='9',name='MODE',func=pin_types.INPUT,unit=1),
            Pin(num='10',name='INTVCC',func=pin_types.PWROUT,unit=1),
            Pin(num='11',name='EXTVCC',func=pin_types.PWRIN,unit=1),
            Pin(num='12',name='VIN',func=pin_types.PWRIN,unit=1),
            Pin(num='13',name='BG',func=pin_types.OUTPUT,unit=1),
            Pin(num='14',name='BOOST',func=pin_types.PASSIVE,unit=1),
            Pin(num='15',name='TG',func=pin_types.OUTPUT,unit=1),
            Pin(num='16',name='SW',func=pin_types.PASSIVE,unit=1),
            Pin(num='17',name='GND',func=pin_types.PWRIN,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'2N7002', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'2N7002'}), 'ref_prefix':'Q', 'fplist':['', 'Package_TO_SOT_SMD:SOT-23'], 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':'N-Channel Switching MOSFET', 'description':'0.115A Id, 60V Vds, N-Channel MOSFET, SOT-23', 'datasheet':'https://www.onsemi.com/pub/Collateral/NDS7002A-D.PDF', 'pins':[
            Pin(num='1',name='G',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='D',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'D_Schottky', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'D_Schottky'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'Diode_SMD:D_SOD-323', 'keywords':'diode Schottky', 'description':'Schottky diode', 'datasheet':'', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'CSD18531Q5A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'CSD18531Q5A'}), 'ref_prefix':'Q', 'fplist':['', 'Package_TO_SOT_SMD:TDSON-8-1'], 'footprint':'Package_TO_SOT_SMD:TDSON-8-1', 'keywords':'NexFET Power MOSFET N-MOS', 'description':'100A Id, 60V Vds, NexFET N-Channel Power MOSFET, 4.6mOhm Ron, 36nC Qg(typ), SON8 5x6mm', 'datasheet':'http://www.ti.com/lit/gpn/csd18531q5a', 'pins':[
            Pin(num='1',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='G',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='D',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C_Polarized', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C_Polarized'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_THT:CP_Radial_D10.0mm_P5.00mm', 'keywords':'cap capacitor', 'description':'Polarized capacitor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'L', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'L'}), 'ref_prefix':'L', 'fplist':[''], 'footprint':'supply1:L_Coilcraft_SER2918H', 'keywords':'inductor choke coil reactor magnetic', 'description':'Inductor', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'INA240A3PW', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'INA240A3PW'}), 'ref_prefix':'U', 'fplist':['Package_SO:TSSOP-8_4.4x3mm_P0.65mm', 'Package_SO:TSSOP-8_4.4x3mm_P0.65mm'], 'footprint':'Package_SO:TSSOP-8_4.4x3mm_P0.65mm', 'keywords':'current monitor shunt sensor bidirectional high low', 'description':'High- and Low-Side, Bidirectional, Zero-Drift, Current-Sense Amplifier With Enhanced PWM Rejection, 100V/V, TSSOP-8', 'datasheet':'http://www.ti.com/lit/ds/symlink/ina240.pdf', 'pins':[
            Pin(num='1',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='+',func=pin_types.INPUT,unit=1),
            Pin(num='3',name='-',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='5',name='V+',func=pin_types.PWRIN,unit=1),
            Pin(num='6',name='REF2',func=pin_types.PASSIVE,unit=1),
            Pin(num='7',name='REF1',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',func=pin_types.OUTPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'ADA4522-2', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ADA4522-2'}), 'ref_prefix':'U', 'fplist':['', ''], 'footprint':'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', 'keywords':'analog-devices opamp chopper', 'description':'55 V supply, 5uV max Vos, 3MHz GBW, EMI Enhanced, Zero Drift, 5.8 nV/â\x88\x9aHz, RRO dual operational amplifiers', 'datasheet':'https://www.analog.com/media/en/technical-documentation/data-sheets/ada4522-1_4522-2_4522-4.pdf', 'pins':[
            Pin(num='1',func=pin_types.OUTPUT,unit=1),
            Pin(num='2',name='-',func=pin_types.INPUT,unit=1),
            Pin(num='3',name='+',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='+',func=pin_types.INPUT,unit=2),
            Pin(num='6',name='-',func=pin_types.INPUT,unit=2),
            Pin(num='7',func=pin_types.OUTPUT,unit=2),
            Pin(num='4',name='V-',func=pin_types.PWRIN,unit=3),
            Pin(num='8',name='V+',func=pin_types.PWRIN,unit=3)], 'unit_defs':[{'label': 'uA', 'num': 1, 'pin_nums': ['3', '2', '1']},{'label': 'uB', 'num': 2, 'pin_nums': ['7', '6', '5']},{'label': 'uC', 'num': 3, 'pin_nums': ['4', '8']}] }),
        Part(**{ 'name':'BC857', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BC857'}), 'ref_prefix':'Q', 'fplist':['', 'Package_TO_SOT_SMD:SOT-23'], 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':'PNP transistor', 'description':'0.1A Ic, 45V Vce, PNP Transistor, SOT-23', 'datasheet':'https://www.onsemi.com/pub/Collateral/BC860-D.pdf', 'pins':[
            Pin(num='1',name='B',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='E',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='C',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'BAT54S', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BAT54S'}), 'ref_prefix':'D', 'fplist':['Package_TO_SOT_SMD:SOT-23'], 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':'schottky diode', 'description':'Vr 30V, If 200mA, Dual schottky barrier diode, in series, SOT-323', 'datasheet':'https://www.diodes.com/assets/Datasheets/ds11005.pdf', 'pins':[
            Pin(num='1',name='A',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='COM',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'LMV331', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LMV331'}), 'ref_prefix':'U', 'fplist':[''], 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':'single comparator', 'description':'Single General-Purpose Low-Voltage Comparator, SOT-23-5/SC-70-5', 'datasheet':'http://www.ti.com/lit/ds/symlink/lmv331.pdf', 'pins':[
            Pin(num='1',name='+',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='V-',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='-',func=pin_types.INPUT,unit=1),
            Pin(num='4',func=pin_types.OPENCOLL,unit=1),
            Pin(num='5',name='V+',func=pin_types.PWRIN,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'UCC27511ADBV', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'UCC27511ADBV'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-23-6'], 'footprint':'Package_TO_SOT_SMD:SOT-23-6', 'keywords':'single channel low side gate drive dual input split output', 'description':'Single-Channel High-Speed Low-Side Gate Driver With 4-A Peak Source and 8-A Peak Sink, SOT-23-6', 'datasheet':'https://www.ti.com/lit/ds/symlink/ucc27511a.pdf', 'pins':[
            Pin(num='1',name='V_{DD}',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='OUTH',func=pin_types.OUTPUT,unit=1),
            Pin(num='3',name='OUTL',func=pin_types.OUTPUT,unit=1),
            Pin(num='4',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='5',name='IN-',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='IN+',func=pin_types.INPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'VOM1271', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'VOM1271'}), 'ref_prefix':'U', 'fplist':['Package_SO:SO-4_4.4x3.6mm_P2.54mm'], 'footprint':'Package_SO:SO-4_4.4x3.6mm_P2.54mm', 'keywords':'', 'description':'Photovoltaic MOSFET driver with fast turn-off', 'datasheet':'', 'pins':[
            Pin(num='1',name='A',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='VO-',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='VO+',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Fuse', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Fuse'}), 'ref_prefix':'F', 'fplist':[''], 'footprint':'Fuse:Fuseholder_Blade_Mini_Keystone_3568', 'keywords':'fuse', 'description':'Fuse', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'D_Schottky_Dual_CommonCathode_AKA', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'D_Schottky_Dual_CommonCathode_AKA'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'Package_TO_SOT_SMD:TO-263-3_TabPin2', 'keywords':'diode', 'description':'Dual Schottky diode, common cathode on pin 2', 'datasheet':'', 'pins':[
            Pin(num='1',name='A',func=pin_types.PASSIVE),
            Pin(num='2',name='K',func=pin_types.PASSIVE),
            Pin(num='3',name='A',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'MountingHole_Pad', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MountingHole_Pad'}), 'ref_prefix':'H', 'fplist':[''], 'footprint':'MountingHole:MountingHole_4.3mm_M4_Pad_Via', 'keywords':'mounting hole', 'description':'Mounting Hole with connection', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.INPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'LMR38010', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LMR38010'}), 'ref_prefix':'U', 'fplist':['Package_SO:TI_SO-PowerPAD-8_ThermalVias'], 'footprint':'Package_SO:TI_SO-PowerPAD-8_ThermalVias', 'keywords':'', 'description':'4.2-80 V 1 A synchronous buck', 'datasheet':'', 'pins':[
            Pin(num='1',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='EN',func=pin_types.INPUT,unit=1),
            Pin(num='3',name='VIN',func=pin_types.PWRIN,unit=1),
            Pin(num='4',name='RT',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='FB',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='PG',func=pin_types.OPENCOLL,unit=1),
            Pin(num='7',name='BOOT',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',name='SW',func=pin_types.PWROUT,unit=1),
            Pin(num='9',name='EP',func=pin_types.PWRIN,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'FerriteBead_Small', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'FerriteBead_Small'}), 'ref_prefix':'FB', 'fplist':[''], 'footprint':'Inductor_SMD:L_0603_1608Metric', 'keywords':'L ferrite bead inductor filter', 'description':'Ferrite bead, small symbol', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'LM5164DDA', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LM5164DDA'}), 'ref_prefix':'U', 'fplist':['Package_SO:HSOP-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.1mm_ThermalVias'], 'footprint':'Package_SO:HSOP-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.1mm_ThermalVias', 'keywords':'step-down dc-dc buck regulator adjustable', 'description':'1A synchronous buck converter with ultra-low IQ, 6V - 100V input, adjustable output voltage, HSOP-8', 'datasheet':'https://www.ti.com/lit/ds/symlink/lm5164.pdf?ts=1598311864250&ref_url=https%253A%252F%252Fwww.ti.com%252Fproduct%252FLM5164%253FHQS%253DTI-null-null-octopart-df-pf-null-wwe', 'pins':[
            Pin(num='1',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='VIN',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='EN/UVLO',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='RON',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='FB',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='PGOOD',func=pin_types.OPENCOLL,unit=1),
            Pin(num='7',name='BST',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',name='SW',func=pin_types.PWROUT,unit=1),
            Pin(num='9',name='EP',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'LP2985-5.0', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LP2985-5.0'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-23-5', 'Package_TO_SOT_SMD:SOT-23-5'], 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':'LDO regulator linear  SOT-23-5', 'description':'150mA 16V Low-noise Low-dropout Regulator With Shutdown, 5.0V output voltage, SOT-23-5', 'datasheet':'http://www.ti.com/lit/ds/symlink/lp2985.pdf', 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='ON/~{OFF}',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='BP',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='VOUT',func=pin_types.PWROUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x04', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x04'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector:FanPinHeader_1x04_P2.54mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x04, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'USBLC6-2SC6', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USBLC6-2SC6'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-666', 'Package_TO_SOT_SMD:SOT-23-6'], 'footprint':'Package_TO_SOT_SMD:SOT-23-6', 'keywords':'usb ethernet video', 'description':'Very low capacitance ESD protection diode, 2 data-line, SOT-23-6', 'datasheet':'https://www.st.com/resource/en/datasheet/usblc6-2.pdf', 'pins':[
            Pin(num='1',name='I/O1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='I/O2',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='I/O2',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='I/O1',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'ADUM3160', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ADUM3160'}), 'ref_prefix':'U', 'fplist':['Package_SO:SOIC-16W_7.5x10.3mm_P1.27mm', 'Package_SO:SOIC-16W_7.5x10.3mm_P1.27mm'], 'footprint':'Package_SO:SOIC-16W_7.5x10.3mm_P1.27mm', 'keywords':'usb isolation', 'description':'Full/Low Speed, iCoupler USB Digital Isolator, 2.5kV protection', 'datasheet':'https://www.analog.com/media/en/technical-documentation/data-sheets/ADuM3160.pdf', 'pins':[
            Pin(num='1',name='VBUS1',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='GND1',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='VDD1',func=pin_types.PWRIN,unit=1),
            Pin(num='4',name='PDEN',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='SPU',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='UD-',func=pin_types.BIDIR,unit=1),
            Pin(num='7',name='UD+',func=pin_types.BIDIR,unit=1),
            Pin(num='8',name='GND1',func=pin_types.PWRIN,unit=1),
            Pin(num='9',name='GND2',func=pin_types.PWRIN,unit=1),
            Pin(num='10',name='DD+',func=pin_types.BIDIR,unit=1),
            Pin(num='11',name='DD-',func=pin_types.BIDIR,unit=1),
            Pin(num='12',name='PIN',func=pin_types.INPUT,unit=1),
            Pin(num='13',name='SPD',func=pin_types.INPUT,unit=1),
            Pin(num='14',name='VDD2',func=pin_types.PWRIN,unit=1),
            Pin(num='15',name='GND2',func=pin_types.PWRIN,unit=1),
            Pin(num='16',name='VBUS2',func=pin_types.PWRIN,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'B0505S-1WR3', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'B0505S-1WR3'}), 'ref_prefix':'PS', 'fplist':['Connector_PinHeader_2.54mm:PinHeader_1x04_P2.54mm_Vertical'], 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x04_P2.54mm_Vertical', 'keywords':'', 'description':'1 W isolated DC-DC 5 V -> 5 V', 'datasheet':'', 'pins':[
            Pin(num='1',name='GND_IN',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='VIN',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='0V_OUT',func=pin_types.PWROUT,unit=1),
            Pin(num='4',name='VOUT',func=pin_types.PWROUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'STM32G474RETx', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'STM32G474RETx'}), 'ref_prefix':'U', 'fplist':['Package_QFP:LQFP-64_10x10mm_P0.5mm', 'Package_QFP:LQFP-64_10x10mm_P0.5mm'], 'footprint':'Package_QFP:LQFP-64_10x10mm_P0.5mm', 'keywords':'Arm Cortex-M4 STM32G4 STM32G4x4', 'description':'STMicroelectronics Arm Cortex-M4 MCU, 512KB flash, 128KB RAM, 170 MHz, 1.71-3.6V, 52 GPIO, LQFP64', 'datasheet':'https://www.st.com/resource/en/datasheet/stm32g474re.pdf', 'pins':[
            Pin(num='1',name='VBAT',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='PC13',func=pin_types.BIDIR,unit=1),
            Pin(num='3',name='PC14',func=pin_types.BIDIR,unit=1),
            Pin(num='4',name='PC15',func=pin_types.BIDIR,unit=1),
            Pin(num='5',name='PF0',func=pin_types.BIDIR,unit=1),
            Pin(num='6',name='PF1',func=pin_types.BIDIR,unit=1),
            Pin(num='7',name='PG10',func=pin_types.BIDIR,unit=1),
            Pin(num='8',name='PC0',func=pin_types.BIDIR,unit=1),
            Pin(num='9',name='PC1',func=pin_types.BIDIR,unit=1),
            Pin(num='10',name='PC2',func=pin_types.BIDIR,unit=1),
            Pin(num='11',name='PC3',func=pin_types.BIDIR,unit=1),
            Pin(num='12',name='PA0',func=pin_types.BIDIR,unit=1),
            Pin(num='13',name='PA1',func=pin_types.BIDIR,unit=1),
            Pin(num='14',name='PA2',func=pin_types.BIDIR,unit=1),
            Pin(num='15',name='VSS',func=pin_types.PWRIN,unit=1),
            Pin(num='16',name='VDD',func=pin_types.PWRIN,unit=1),
            Pin(num='17',name='PA3',func=pin_types.BIDIR,unit=1),
            Pin(num='18',name='PA4',func=pin_types.BIDIR,unit=1),
            Pin(num='19',name='PA5',func=pin_types.BIDIR,unit=1),
            Pin(num='20',name='PA6',func=pin_types.BIDIR,unit=1),
            Pin(num='21',name='PA7',func=pin_types.BIDIR,unit=1),
            Pin(num='22',name='PC4',func=pin_types.BIDIR,unit=1),
            Pin(num='23',name='PC5',func=pin_types.BIDIR,unit=1),
            Pin(num='24',name='PB0',func=pin_types.BIDIR,unit=1),
            Pin(num='25',name='PB1',func=pin_types.BIDIR,unit=1),
            Pin(num='26',name='PB2',func=pin_types.BIDIR,unit=1),
            Pin(num='27',name='VSSA',func=pin_types.PWRIN,unit=1),
            Pin(num='28',name='VREF+',func=pin_types.INPUT,unit=1),
            Pin(num='29',name='VDDA',func=pin_types.PWRIN,unit=1),
            Pin(num='30',name='PB10',func=pin_types.BIDIR,unit=1),
            Pin(num='31',name='VSS',func=pin_types.PASSIVE,unit=1),
            Pin(num='32',name='VDD',func=pin_types.PWRIN,unit=1),
            Pin(num='33',name='PB11',func=pin_types.BIDIR,unit=1),
            Pin(num='34',name='PB12',func=pin_types.BIDIR,unit=1),
            Pin(num='35',name='PB13',func=pin_types.BIDIR,unit=1),
            Pin(num='36',name='PB14',func=pin_types.BIDIR,unit=1),
            Pin(num='37',name='PB15',func=pin_types.BIDIR,unit=1),
            Pin(num='38',name='PC6',func=pin_types.BIDIR,unit=1),
            Pin(num='39',name='PC7',func=pin_types.BIDIR,unit=1),
            Pin(num='40',name='PC8',func=pin_types.BIDIR,unit=1),
            Pin(num='41',name='PC9',func=pin_types.BIDIR,unit=1),
            Pin(num='42',name='PA8',func=pin_types.BIDIR,unit=1),
            Pin(num='43',name='PA9',func=pin_types.BIDIR,unit=1),
            Pin(num='44',name='PA10',func=pin_types.BIDIR,unit=1),
            Pin(num='45',name='PA11',func=pin_types.BIDIR,unit=1),
            Pin(num='46',name='PA12',func=pin_types.BIDIR,unit=1),
            Pin(num='47',name='VSS',func=pin_types.PASSIVE,unit=1),
            Pin(num='48',name='VDD',func=pin_types.PWRIN,unit=1),
            Pin(num='49',name='PA13',func=pin_types.BIDIR,unit=1),
            Pin(num='50',name='PA14',func=pin_types.BIDIR,unit=1),
            Pin(num='51',name='PA15',func=pin_types.BIDIR,unit=1),
            Pin(num='52',name='PC10',func=pin_types.BIDIR,unit=1),
            Pin(num='53',name='PC11',func=pin_types.BIDIR,unit=1),
            Pin(num='54',name='PC12',func=pin_types.BIDIR,unit=1),
            Pin(num='55',name='PD2',func=pin_types.BIDIR,unit=1),
            Pin(num='56',name='PB3',func=pin_types.BIDIR,unit=1),
            Pin(num='57',name='PB4',func=pin_types.BIDIR,unit=1),
            Pin(num='58',name='PB5',func=pin_types.BIDIR,unit=1),
            Pin(num='59',name='PB6',func=pin_types.BIDIR,unit=1),
            Pin(num='60',name='PB7',func=pin_types.BIDIR,unit=1),
            Pin(num='61',name='PB8',func=pin_types.BIDIR,unit=1),
            Pin(num='62',name='PB9',func=pin_types.BIDIR,unit=1),
            Pin(num='63',name='VSS',func=pin_types.PASSIVE,unit=1),
            Pin(num='64',name='VDD',func=pin_types.PWRIN,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'SW_Push', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SW_Push'}), 'ref_prefix':'SW', 'fplist':[''], 'footprint':'Button_Switch_THT:SW_PUSH_6mm', 'keywords':'switch normally-open pushbutton push-button', 'description':'Push button switch, generic, two pins', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_02x05_Odd_Even', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_02x05_Odd_Even'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_PinHeader_1.27mm:PinHeader_2x05_P1.27mm_Vertical', 'keywords':'connector', 'description':'Generic connector, double row, 02x05, odd/even pin numbering scheme (row 1 odd numbers, row 2 even numbers), script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='Pin_5',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='Pin_6',func=pin_types.PASSIVE,unit=1),
            Pin(num='7',name='Pin_7',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',name='Pin_8',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',name='Pin_9',func=pin_types.PASSIVE,unit=1),
            Pin(num='10',name='Pin_10',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_02x13_Odd_Even', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_02x13_Odd_Even'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_IDC:IDC-Header_2x13_P2.54mm_Vertical', 'keywords':'connector', 'description':'Generic connector, double row, 02x13, odd/even pin numbering scheme (row 1 odd numbers, row 2 even numbers), script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='Pin_5',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='Pin_6',func=pin_types.PASSIVE,unit=1),
            Pin(num='7',name='Pin_7',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',name='Pin_8',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',name='Pin_9',func=pin_types.PASSIVE,unit=1),
            Pin(num='10',name='Pin_10',func=pin_types.PASSIVE,unit=1),
            Pin(num='11',name='Pin_11',func=pin_types.PASSIVE,unit=1),
            Pin(num='12',name='Pin_12',func=pin_types.PASSIVE,unit=1),
            Pin(num='13',name='Pin_13',func=pin_types.PASSIVE,unit=1),
            Pin(num='14',name='Pin_14',func=pin_types.PASSIVE,unit=1),
            Pin(num='15',name='Pin_15',func=pin_types.PASSIVE,unit=1),
            Pin(num='16',name='Pin_16',func=pin_types.PASSIVE,unit=1),
            Pin(num='17',name='Pin_17',func=pin_types.PASSIVE,unit=1),
            Pin(num='18',name='Pin_18',func=pin_types.PASSIVE,unit=1),
            Pin(num='19',name='Pin_19',func=pin_types.PASSIVE,unit=1),
            Pin(num='20',name='Pin_20',func=pin_types.PASSIVE,unit=1),
            Pin(num='21',name='Pin_21',func=pin_types.PASSIVE,unit=1),
            Pin(num='22',name='Pin_22',func=pin_types.PASSIVE,unit=1),
            Pin(num='23',name='Pin_23',func=pin_types.PASSIVE,unit=1),
            Pin(num='24',name='Pin_24',func=pin_types.PASSIVE,unit=1),
            Pin(num='25',name='Pin_25',func=pin_types.PASSIVE,unit=1),
            Pin(num='26',name='Pin_26',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'MountingHole', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MountingHole'}), 'ref_prefix':'H', 'fplist':[''], 'footprint':'MountingHole:MountingHole_3.2mm_M3', 'keywords':'mounting hole', 'description':'Mounting Hole without connection', 'datasheet':'' })])